/*
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.

*/

public class Solution {
    public char findTheDifference(String s, String t) {
        /*
        Solution in Discussion:
        using bit manipulation to filter the added extra letter
        x ^ 0 = x
        x ^ x = 0
        */
        int size = s.length();
        char c = t.charAt(size);
        for (int i=0; i<s.length(); i++){
            c ^= s.charAt(i);
            c ^= t.charAt(i);
        }
        return c;
    }
}